"""Cargo test driver — runs CC-generated Rust integration test files via `cargo test`.

CC writes a Rust integration test file like:
    mod validation_params;
    use validation_params::{get_validation_test_cases, TestCase};
    use spacetimedb_table::table_index::hash_index::HashIndex;

    #[test]
    fn test_hash_index_point_lookup() {
        let cases = get_validation_test_cases();
        for (i, tc) in cases.iter().enumerate() {
            // exercise the code using tc.inputs and tc.expected
        }
    }

The get_validation_test_cases helper is generated by the driver and reads
from the immutable params file. CC cannot modify the expected values.

Story-level fields:
- `cargo_package`: crate directory relative to repo (e.g., "crates/table")
- `cargo_module_dir`: workspace root if different from repo root (optional)
"""

from __future__ import annotations

from pathlib import Path

from .base import CaseResult, Driver, DriverResult, map_run_result_to_cases

# Rust helper module that CC's test files import, written into the target
# crate's tests/ directory alongside CC's test file.
PARAMS_HELPER_TEMPLATE = """\
use serde::Deserialize;
use serde_json::Value;
use std::fs;

#[derive(Debug, Deserialize)]
struct ParamsFile {
    test_cases: Vec<RawTestCase>,
}

#[derive(Debug, Deserialize)]
struct RawTestCase {
    inputs: Value,
    expected: Value,
}

#[derive(Debug)]
pub struct TestCase {
    pub name: String,
    pub inputs: Value,
    pub expected: Value,
}

pub fn get_validation_test_cases() -> Vec<TestCase> {
    let path = std::env::var("VALIDATION_PARAMS")
        .expect("VALIDATION_PARAMS env var not set");
    let data = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read params file {path}: {e}"));
    let params: ParamsFile = serde_json::from_str(&data)
        .unwrap_or_else(|e| panic!("failed to parse params file {path}: {e}"));
    params
        .test_cases
        .into_iter()
        .enumerate()
        .map(|(i, tc)| TestCase {
            name: format!("case_{i}"),
            inputs: tc.inputs,
            expected: tc.expected,
        })
        .collect()
}
"""


class CargoTestDriver(Driver):
    """Runs CC-generated Rust integration test files via `cargo test`."""

    script_extension = "_test.rs"

    def execute_story(
        self,
        story: dict,
        scripts_dir: Path,
        logs_dir: Path,
        repo_dir: Path,
        timeout: int = 300,
        spec_settings: dict | None = None,
    ) -> DriverResult:
        from ..runners.rust import RustRunConfig, run

        sid = story["id"]
        test_cases = self._get_test_cases(story)
        result = DriverResult(story_id=sid)

        cargo_package = story.get("cargo_package", "")
        crate_dir = repo_dir / cargo_package if cargo_package else None

        if not cargo_package or not crate_dir or not crate_dir.exists():
            result.cases.append(
                CaseResult(
                    case_index=0,
                    passed=False,
                    reason=f"cargo_package '{cargo_package}' not found at {crate_dir}",
                )
            )
            return result

        script_path = self._get_script_path(story, scripts_dir)
        if not script_path.exists():
            result.cases.append(CaseResult(case_index=0, passed=False, reason="Test file not generated"))
            return result

        if not test_cases:
            result.cases.append(CaseResult(case_index=0, passed=False, reason="No test cases"))
            return result

        params_path = self.write_params_file(test_cases, logs_dir, sid)
        helper_path = logs_dir / "validation_params.rs"
        helper_path.write_text(PARAMS_HELPER_TEMPLATE)

        cargo_settings = (spec_settings or {}).get("cargo-test", {})
        run_env = {"VALIDATION_PARAMS": str(params_path)}
        for k, v in cargo_settings.get("env", {}).items():
            run_env[str(k)] = str(v)

        try:
            run_result = run(
                RustRunConfig(
                    test_file=script_path,
                    repo_dir=repo_dir,
                    crate=cargo_package,
                    workspace_dir=story.get("cargo_module_dir", ""),
                    timeout=timeout,
                    env=run_env,
                    command=cargo_settings.get("command", "cargo test"),
                    extra_args=cargo_settings.get("extra_args", ""),
                    extra_files=[helper_path],
                )
            )
        finally:
            helper_path.unlink(missing_ok=True)

        result.cases = map_run_result_to_cases(run_result, len(test_cases), "cargo test")
        return result
