"""Go test driver — runs CC-generated Go test files via `go test`.

CC writes a _test.go file like:
    package joining_test

    import (
        "testing"
        "github.com/stretchr/testify/require"
    )

    func TestImmutableLabels(t *testing.T) {
        cases := GetValidationTestCases(t)
        for _, tc := range cases {
            t.Run(tc.Name, func(t *testing.T) {
                // exercise the code using tc.Inputs and tc.Expected
            })
        }
    }

The GetValidationTestCases helper is generated by the driver and reads
from the immutable params file. CC cannot modify the expected values.

Stories run one at a time. Any sibling .go file declaring NO `func TestXxx`
is treated as a shared helper and injected alongside the current story's
file; files that DO declare a Test function are other stories and are never
injected together.

Settings (from `[settings.go]` in validation_spec.toml):
- `build_tags`: build tags passed to `go test -tags ...` (e.g.
  ["sqlite", "sqlite_unlock_notify"] for gitea's cgo sqlite test build)
- `command`: the base test command (default "go test")
- `env`: extra environment variables for the test process

Story-level settings:
- `go_package`: package directory relative to repo (e.g., "lib/scopes/joining")
- `go_module_dir`: which Go module root to use (default: repo root).
  Some repos have multiple modules (e.g., Teleport has /repo/teleport and
  /repo/teleport/api as separate modules).
"""

from __future__ import annotations

from pathlib import Path

from .base import CaseResult, Driver, DriverResult, map_run_result_to_cases

# Go helper that CC's test files call to get params, written into the target
# package directory alongside CC's test file.
PARAMS_HELPER_TEMPLATE = """\
package {package_name}

import (
\t"encoding/json"
\t"fmt"
\t"os"
\t"testing"
)

// ValidationTestCase holds a single test case from the spec author's params.
type ValidationTestCase struct {{
\tName     string
\tInputs   map[string]interface{{}}
\tExpected map[string]interface{{}}
}}

// GetValidationTestCases reads the immutable params file and returns test cases.
// Call this from your test function to get the spec author's parameterized inputs.
func GetValidationTestCases(t *testing.T) []ValidationTestCase {{
\tt.Helper()
\tpath := os.Getenv("VALIDATION_PARAMS")
\tif path == "" {{
\t\tt.Skip("VALIDATION_PARAMS not set")
\t}}
\tdata, err := os.ReadFile(path)
\tif err != nil {{
\t\tt.Fatalf("failed to read params file: %v", err)
\t}}
\tvar raw struct {{
\t\tTestCases []struct {{
\t\t\tInputs   map[string]interface{{}} `json:"inputs"`
\t\t\tExpected map[string]interface{{}} `json:"expected"`
\t\t}} `json:"test_cases"`
\t}}
\tif err := json.Unmarshal(data, &raw); err != nil {{
\t\tt.Fatalf("failed to parse params file: %v", err)
\t}}
\tcases := make([]ValidationTestCase, len(raw.TestCases))
\tfor i, tc := range raw.TestCases {{
\t\tcases[i] = ValidationTestCase{{
\t\t\tName:     fmt.Sprintf("case_%d", i),
\t\t\tInputs:   tc.Inputs,
\t\t\tExpected: tc.Expected,
\t\t}}
\t}}
\treturn cases
}}
"""


class GoTestDriver(Driver):
    """Runs CC-generated Go test files via `go test -json`."""

    script_extension = "_test.go"

    def execute_story(
        self,
        story: dict,
        scripts_dir: Path,
        logs_dir: Path,
        repo_dir: Path,
        timeout: int = 300,
        spec_settings: dict | None = None,
    ) -> DriverResult:
        from ..runners.go import GoRunConfig, find_test_func, read_package_name, run

        sid = story["id"]
        test_cases = self._get_test_cases(story)
        result = DriverResult(story_id=sid)

        go_package = story.get("go_package", "")
        go_module_dir = story.get("go_module_dir", "")
        package_dir = repo_dir / go_package if go_package else None

        if not go_package or not package_dir or not package_dir.exists():
            result.cases.append(
                CaseResult(
                    case_index=0,
                    passed=False,
                    reason=f"go_package '{go_package}' not found at {package_dir}",
                )
            )
            return result

        script_path = self._get_script_path(story, scripts_dir)
        if not script_path.exists():
            result.cases.append(CaseResult(case_index=0, passed=False, reason="Test file not generated"))
            return result

        if not test_cases:
            result.cases.append(CaseResult(case_index=0, passed=False, reason="No test cases"))
            return result

        params_path = self.write_params_file(test_cases, logs_dir, sid)
        package_name = read_package_name(script_path, package_dir)
        helper_path = logs_dir / "validation_params_test.go"
        helper_path.write_text(PARAMS_HELPER_TEMPLATE.format(package_name=package_name))

        go_settings = (spec_settings or {}).get("go", {})
        run_env = {"VALIDATION_PARAMS": str(params_path)}
        for k, v in go_settings.get("env", {}).items():
            run_env[str(k)] = str(v)

        # Sibling .go files with no `func TestXxx` are shared helpers; inject
        # them so the story file compiles. Other stories' files are excluded.
        helper_files = [
            p
            for p in sorted(scripts_dir.glob("*.go"))
            if p.resolve() != script_path.resolve() and not find_test_func(p)
        ]

        try:
            run_result = run(
                GoRunConfig(
                    test_file=script_path,
                    repo_dir=repo_dir,
                    package=go_package,
                    module_dir=go_module_dir,
                    run=find_test_func(script_path),
                    timeout=timeout,
                    env=run_env,
                    command=go_settings.get("command", "go test"),
                    build_tags=go_settings.get("build_tags", []),
                    extra_files=[helper_path, *helper_files],
                )
            )
        finally:
            helper_path.unlink(missing_ok=True)

        result.cases = map_run_result_to_cases(run_result, len(test_cases), "go test")
        return result
