"""Pytest driver — runs CC-generated pytest files with runtime-injected params.

The driver generates a conftest.py that provides `inputs` and `expected`
fixtures (parametrized from the immutable params file), runs pytest on CC's
test file, and parses per-case pass/fail.

CC writes a test file like:
    def test_detect_currency(inputs, expected):
        result = detect_currency_from_df(build_df(inputs["values"]))
        assert result == expected["detected_currency"]

The `inputs` and `expected` fixtures are injected by the driver's conftest.
CC cannot modify the expected values — they come from the spec author's
immutable params file.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

from .base import CaseResult, Driver, DriverResult

# Template for the driver-generated conftest.py
CONFTEST_TEMPLATE = '''\
"""Driver-generated conftest.py — provides validation params as pytest fixtures.

DO NOT MODIFY. This file is generated by the validation driver and reads
test parameters from an immutable JSON file.
"""
import json
import os
import pytest


def _load_params():
    path = os.environ.get("VALIDATION_PARAMS")
    if not path:
        pytest.skip("VALIDATION_PARAMS not set")
    with open(path) as f:
        return json.load(f)


def pytest_generate_tests(metafunc):
    """Parametrize test functions that use `inputs` and `expected` fixtures."""
    if "inputs" in metafunc.fixturenames and "expected" in metafunc.fixturenames:
        params = _load_params()
        cases = params.get("test_cases", [])
        argvalues = [
            (c.get("inputs", {}), c.get("expected", {}))
            for c in cases
        ]
        metafunc.parametrize(
            "inputs,expected",
            argvalues,
            ids=[f"case_{i}" for i in range(len(cases))],
        )
'''

# Django variant: enables database access via autouse fixture
CONFTEST_DJANGO_TEMPLATE = '''\
"""Driver-generated conftest.py — Django-aware validation params fixtures.

DO NOT MODIFY. This file is generated by the validation driver and reads
test parameters from an immutable JSON file.
Includes autouse db fixture so all tests can access the database.
"""
import json
import os
import pytest


def pytest_collection_modifyitems(items):
    """Mark all tests with django_db(databases='__all__') so multi-DB repos
    (e.g. PostHog with persons_db_writer) don't hit DatabaseOperationForbidden."""
    import pytest
    marker = pytest.mark.django_db(databases="__all__")
    for item in items:
        item.add_marker(marker)


def _load_params():
    path = os.environ.get("VALIDATION_PARAMS")
    if not path:
        pytest.skip("VALIDATION_PARAMS not set")
    with open(path) as f:
        return json.load(f)


def pytest_generate_tests(metafunc):
    """Parametrize test functions that use `inputs` and `expected` fixtures."""
    if "inputs" in metafunc.fixturenames and "expected" in metafunc.fixturenames:
        params = _load_params()
        cases = params.get("test_cases", [])
        argvalues = [
            (c.get("inputs", {}), c.get("expected", {}))
            for c in cases
        ]
        metafunc.parametrize(
            "inputs,expected",
            argvalues,
            ids=[f"case_{i}" for i in range(len(cases))],
        )
'''


class PytestDriver(Driver):
    """Runs CC-generated pytest files with runtime-injected params."""

    script_extension = ".py"

    def execute_story(
        self,
        story: dict,
        scripts_dir: Path,
        logs_dir: Path,
        repo_dir: Path,
        timeout: int = 300,
        spec_settings: dict | None = None,
    ) -> DriverResult:
        sid = story["id"]
        test_cases = self._get_test_cases(story)
        result = DriverResult(story_id=sid)

        script_path = self._get_script_path(story, scripts_dir)
        if not script_path.exists():
            result.cases.append(
                CaseResult(
                    case_index=0,
                    passed=False,
                    reason="Test file not generated",
                )
            )
            return result

        if not test_cases:
            result.cases.append(
                CaseResult(
                    case_index=0,
                    passed=False,
                    reason="No test cases",
                )
            )
            return result

        params_path = self.write_params_file(test_cases, logs_dir, sid)

        # Extracted early because conftest selection depends on django_settings.
        pytest_settings = (spec_settings or {}).get("pytest", {})
        django_settings = pytest_settings.get("django_settings")

        # Write driver conftest.py alongside CC's test file. A task-provided
        # /tests/validate/conftest_override.py is copied next to it and
        # registered as a plugin, letting tasks add custom fixtures without
        # reimplementing the parametrize/marker logic.
        conftest_path = scripts_dir / "conftest.py"
        if not conftest_path.exists():
            base = CONFTEST_DJANGO_TEMPLATE if django_settings else CONFTEST_TEMPLATE
            override_path = Path("/tests/validate/conftest_override.py")
            if override_path.exists():
                import shutil

                shutil.copy(override_path, scripts_dir / "conftest_override.py")
                base = 'pytest_plugins = ["conftest_override"]\n\n' + base
            conftest_path.write_text(base)

        env = {**os.environ}
        env["VALIDATION_PARAMS"] = str(params_path)
        env.setdefault("PYTHONWARNINGS", "ignore")
        tests_dir = Path("/tests")
        validate_dir = tests_dir / "validate"
        path_parts = [str(scripts_dir), str(tests_dir), str(validate_dir), str(repo_dir)]
        for extra in pytest_settings.get("extra_pythonpath", []):
            path_parts.append(str(repo_dir / extra))
        env["PYTHONPATH"] = ":".join(path_parts)

        if django_settings:
            env["DJANGO_SETTINGS_MODULE"] = django_settings

        # Supports multi-word commands like "uv run python".
        python_cmd = pytest_settings.get("python", sys.executable).split()

        cmd = [
            *python_cmd,
            "-m",
            "pytest",
            str(script_path),
            "-v",
            "--tb=short",
            "--no-header",
            f"--rootdir={scripts_dir}",
        ]
        if django_settings:
            cmd.append(f"--ds={django_settings}")

        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout + 30,  # buffer for pytest startup
                cwd=str(repo_dir),
                env=env,
                check=False,
            )

            diag_dir = logs_dir / "diagnostics"
            diag_dir.mkdir(parents=True, exist_ok=True)
            (diag_dir / f"{sid}_pytest_stdout.txt").write_text(proc.stdout[-5000:])
            (diag_dir / f"{sid}_pytest_stderr.txt").write_text(proc.stderr[-5000:])

        except subprocess.TimeoutExpired:
            for i in range(len(test_cases)):
                result.cases.append(
                    CaseResult(
                        case_index=i,
                        passed=False,
                        reason="pytest timed out",
                    )
                )
            return result

        result.cases = self._parse_pytest_output(
            proc.stdout,
            proc.stderr,
            proc.returncode,
            len(test_cases),
        )

        return result

    def _parse_pytest_output(
        self,
        stdout: str,
        stderr: str,
        returncode: int,
        expected_cases: int,
    ) -> list[CaseResult]:
        """Parse pytest -v output to extract per-case pass/fail.

        Pytest verbose output looks like:
            test_file.py::test_func[case_0] PASSED
            test_file.py::test_func[case_1] FAILED
        """
        cases: list[CaseResult] = []
        combined = stdout + "\n" + stderr

        pattern = re.compile(r"::.*\[case_(\d+)\]\s+(PASSED|FAILED|ERROR)")
        found = {}
        for m in pattern.finditer(combined):
            idx = int(m.group(1))
            status = m.group(2)
            found[idx] = status

        # Fall back to matching without case_ prefix (single test, no parametrize).
        if not found and expected_cases == 1:
            if "PASSED" in combined:
                found[0] = "PASSED"
            elif "FAILED" in combined or "ERROR" in combined:
                found[0] = "FAILED"

        # Build results
        for i in range(expected_cases):
            status = found.get(i)
            if status == "PASSED":
                cases.append(CaseResult(case_index=i, passed=True))
            elif status in ("FAILED", "ERROR"):
                reason = self._extract_failure_reason(combined, i)
                cases.append(
                    CaseResult(
                        case_index=i,
                        passed=False,
                        reason=f"Case {i}: {reason}",
                        stdout=stdout[-500:],
                        stderr=stderr[-500:],
                    )
                )
            else:
                # Case didn't run (an earlier case may have caused a collection error).
                cases.append(
                    CaseResult(
                        case_index=i,
                        passed=False,
                        reason=f"Case {i}: not found in pytest output (exit {returncode})",
                        stdout=stdout[-500:],
                        stderr=stderr[-500:],
                    )
                )

        return cases

    def _extract_failure_reason(self, output: str, case_idx: int) -> str:
        """Extract the assertion error message for a specific case."""
        lines = output.splitlines()
        in_failure = False
        reason_lines = []
        for line in lines:
            if f"case_{case_idx}" in line and ("FAILED" in line or "ERROR" in line):
                in_failure = True
                continue
            if in_failure:
                if line.startswith("PASSED") or line.startswith("FAILED") or line.startswith("="):
                    break
                if "AssertionError" in line or "assert" in line.lower() or "E " in line:
                    reason_lines.append(line.strip())
        return "; ".join(reason_lines[:3]) if reason_lines else "assertion failed"
